import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NoCountry',
  description: 'Generated by create next app',
}


const links = [
  {
    label: "Home",
    route: "/"
  },
  {
    label: "About",
    route: "/about"
  }
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            {links.map((link, index) => (
              <li key={index}>
                <a href={link.route}>{link.label}</a>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
